FROM registry.access.redhat.com/ubi8/go-toolset:1.22@sha256:f78db31a9ec928a8ea945b92affd10956c72665d6d67e9fbe23c89efb1f21428 AS builder

WORKDIR /workspace

# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
#RUN go mod download

# Copy the go source
COPY . .

# Build
RUN make build GO_BUILD_ENV='CGO_ENABLED=1 GOOS=linux'

FROM registry.redhat.io/ubi8/ubi-minimal@sha256:b2a1bec3dfbc7a14a1d84d98934dfe8fdde6eb822a211286601cf109cbccb075 AS runtime

## Build args to be used at this step
ARG USER=65532

LABEL com.redhat.component="odh-kueue-controller-container" \
      name="managed-open-data-hub/odh-kueue-controller-rhel8" \
      description="Kueue is a set of APIs and controller for job queueing. It is a job-level manager that decides when a job should be admitted to start (as in pods can be created) and when it should stop (as in active pods should be deleted)." \
      summary="odh-kueue-controller" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-kueue-controller" \
      io.k8s.description="odh-kueue-controller" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"


WORKDIR /
USER root
COPY --from=builder /workspace/bin/manager /manager
USER 65532:65532

ENTRYPOINT ["/manager"]
