FROM FROM registry.access.redhat.com/ubi8/go-toolset:1.25@sha256:070a8b01fe3c47cda74390c49c37e0abde1157c162cc3a46be1698564a18f923 AS builder

WORKDIR /workspace

# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY . .

# Build
RUN make build GO_BUILD_ENV='CGO_ENABLED=1 GOOS=linux'

FROM registry.access.redhat.com/ubi9/ubi:latest

WORKDIR /
USER root
COPY --from=builder /workspace/bin/manager /manager
USER 65532:65532

ENTRYPOINT ["/manager"]