kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kueue-admin-rolebinding
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
      time: '2024-01-30T14:56:22Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:roleRef': {}
        'f:subjects': {}
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: rhods-admins
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: odh-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kueue-batch-admin-role