# Dev/testing friendly settings for Kueue.

# Use default settings as a base.
resources:
- binding_admin_roles.yaml

patches:
# Modify logging for better user experience. 
- path: binding_admin_roles.yaml
